name: Monthly Report

on:
  pull_request:
  workflow_dispatch:

jobs:
  monthly-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send to Slack
        run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#reports\", \"username\": \"webhookbot\", \"text\": \"This is posted to #reports and comes from a bot named webhookbot.\", \"icon_emoji\": \":ghost:\"}" curl -X POST --data-urlencode "payload={\"channel\": \"#reports\", \"username\": \"webhookbot\", \"text\": \"This is posted to #my-channel-here and comes from a bot named webhookbot.\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/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
